---
version: "3.7"

services:
  postgres_gitea:
    image: postgres:alpine
    container_name: ${GITEA_CONTNAME_DB}
    stdin_open: true
    tty: true
    networks:
      gitea-net:
    volumes:
      - ./gitea/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${GITEA_DB_NAME}
      POSTGRES_USER: ${GITEA_DB_USER}
      POSTGRES_PASSWORD: ${GITEA_DB_PASSWORD}
    logging:
      driver: ${LOG_DRIVER:-local}
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "gitea", "-U", "gitea" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  traefik:
    image: traefik:v2.10.4
    stdin_open: true
    tty: true
    networks:
      gitea-net:
        aliases:
          - ${GITEA_DOMAIN:-gitea.owncloud.test}
    command:
      - "--log.level=${TRAEFIK_LOG_LEVEL:-ERROR}"
      # letsencrypt configuration
      - "--certificatesResolvers.http.acme.email=${TRAEFIK_ACME_MAIL:-demo@example.com}"
      - "--certificatesResolvers.http.acme.storage=/certs/acme.json"
      - "--certificatesResolvers.http.acme.httpChallenge.entryPoint=http"
      # enable dashboard
      - "--api.dashboard=true"
      - "--api.insecure=true"
      # enable ping
      - "--ping=true"
      - "--ping.entrypoint=ping"
      # define entrypoints
      - "--entryPoints.ping.address=:8082"
      - "--entryPoints.http.address=:80"
      - "--entryPoints.http.http.redirections.entryPoint.to=https"
      - "--entryPoints.http.http.redirections.entryPoint.scheme=https"
      - "--entryPoints.https.address=:443"
      # docker provider (get configuration from container labels)
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedByDefault=false"
      # access log
      - "--accessLog=true"
      - "--accessLog.format=json"
      - "--accessLog.fields.headers.names.X-Request-Id=keep"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ".certs:/certs"
    labels:
      - "traefik.enable=${TRAEFIK_DASHBOARD:-false}"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_BASIC_AUTH_USERS:-admin:$$apr1$$4vqie50r$$YQAmQdtmz5n9rEALhxJ4l.}" # defaults to admin:admin
      - "traefik.http.routers.traefik.entrypoints=https"
      - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_DOMAIN:-traefik.owncloud.test}`)"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
      - "traefik.http.routers.traefik.tls.certresolver=http"
      - "traefik.http.routers.traefik.service=api@internal"
    logging:
      driver: "local"
    restart: always
    healthcheck:
      test: ["CMD", "wget", "http://localhost:8082/ping","--spider"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  gitea:
    image: gitea/gitea:latest-rootless
    container_name: ${GITEA_CONTNAME_GITEA}
    networks:
      gitea-net:
    environment:
      # Anything in the app.ini can be overridden with environment variables here.
      # The format is: GITEA__<section name>__<key name>
      # The trick part is the keys not in any section like APP_NAME, must follow the format above with empty section name.
      - GITEA____APP_NAME="Auroria Private Gitea"
      - GITEA__repository_DEFAULT_PRIVATE=private
      - GITEA__server__RUN_MODE=dev
      - GITEA__server__DOMAIN=${GITEA_DOMAIN:-gitea.owncloud.test}
      - GITEA__server__HTTP_PORT=3000
      - GITEA__server__ROOT_URL=https://${GITEA_DOMAIN:-gitea.owncloud.test}
      - GITEA__server__DISABLE_SSH=true
      - GITEA__server__LFS_START_SERVER=true
      - GITEA__server__LFS_JWT_SECRET=${GITEA_JWT_SECRET:-hy3gVe5niZxy9SF6z7kn1gVvUMbOwy-bpXjOb7BMb0Q}
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres_gitea:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - GITEA__security__INSTALL_LOCK=true
      - GITEA__security__MIN_PASSWORD_LENGTH=12
      - GITEA__security__PASSWORD_COMPLEXITY=lower,upper,digit,spec
      - GITEA__security__SECRET_KEY=${GITEA_SECRET_KEY:-opfWytJAgRwr71vBXFAIDCA0Cu4DqEnGqa60Fw9l4npgEP6MGFsIJMyddNmLnQj0}
      - GITEA__security__INTERNAL_TOKEN=${GITEA_INTERNAL_TOKEN:-eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE2OTY1MTE0Mzh9.bp-ZZhFrzM6FFh0jccLI9xI0XG7_R0pug2oHAsjNheQ}
      - GITEA__service__DISABLE_REGISTRATION=true
      - GITEA__service.explore__REQUIRE_SIGNIN_VIEW=true
      - GITEA__service.explore__DISABLE_USERS_PAGE=true
      - GITEA__openid__ENABLE_OPENID_SIGNIN=false
      - GITEA__openid__ENABLE_OPENID_SIGNUP=false
      - GITEA__lfs__STORAGE_TYPE=minio
      - GITEA__lfs__SERVE_DIRECT=true
      - GITEA__lfs__MINIO_USE_SSL=true
      - GITEA__lfs__MINIO_CHECKSUM_ALGORITHM=md5
      - GITEA__lfs__MINIO_ENDPOINT=${GITEA_MINIO_ENDPOINT:-localhost:9000}
      - GITEA__lfs__MINIO_ACCESS_KEY_ID=${GITEA_MINIO_ACCESS_KEY_ID:-62bFLvcv2EsGjGhYq7rQ}
      - GITEA__lfs__MINIO_SECRET_ACCESS_KEY=${GITEA_MINIO_SECRET_ACCESS_KEY:-3YOhDJxwXjmtn3cWHQvisGMWS2QFMYahPxYCUlPJ}
      - GITEA__lfs__MINIO_BUCKET=${GITEA_MINIO_BUCKET:-lol1}
      - GITEA__lfs__MINIO_LOCATION=${GITEA_MINIO_LOCATION:-th-central}
    volumes:
      - ./gitea/data:${GITEA_DATA_PATH:-/var/lib/gitea}
      - ./gitea/config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`${GITEA_DOMAIN:-gitea.owncloud.test}`)"
      - "traefik.http.routers.gitea.service=gitea"
      - "traefik.http.routers.gitea.entrypoints=https"
      - "traefik.http.routers.gitea.tls=true"
      - "traefik.http.routers.gitea.tls.certresolver=letsencrypt"
      - "traefik.http.services.gitea.loadbalancer.passhostheader=true"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
    depends_on:
      postgres_gitea:
        condition: service_healthy
      traefik:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/healthz"]
      interval: 60s
      timeout: 50s
      retries: 5
      start_period: 65s

  # This is the local backup solution, ideally with 24 hours interval or below.
  # TODO: Improve this with a tool to upload the files to S3 storage.
  backups:
    image: postgres:alpine
    container_name: gitea-backups
    command: >-
      sh -c 'sleep $BACKUP_INIT_SLEEP &&
      while true; do
        pg_dump -h postgres_gitea -p 5432 -d $GITEA_DB_NAME -U $GITEA_DB_USER | gzip > $GITEA_POSTGRES_BACKUPS_PATH/$GITEA_POSTGRES_BACKUP_NAME-$(date "+%Y-%m-%d_%H-%M").gz &&
        tar -zcpf $GITEA_DATA_BACKUPS_PATH/$GITEA_DATA_BACKUP_NAME-$(date "+%Y-%m-%d_%H-%M").tar.gz $GITEA_DATA_PATH &&
        find $GITEA_POSTGRES_BACKUPS_PATH -type f -mtime +$BACKUP_PRUNE_DAYS | xargs rm -f &&
        find $GITEA_DATA_BACKUPS_PATH -type f -mtime +$BACKUP_PRUNE_DAYS | xargs rm -f;
        sleep $BACKUP_INTERVAL; done'
    volumes:
      - ./gitea/data:${GITEA_DATA_PATH}
      - ./backups/temp-postgres:/var/lib/postgresql/data
      - ./backups/gitea-data:${GITEA_DATA_BACKUPS_PATH}
      - ./backups/gitea-database:${GITEA_POSTGRES_BACKUPS_PATH}
    environment:
      PGPASSWORD: ${GITEA_DB_PASSWORD}
    networks:
      gitea-net:
    restart: unless-stopped
    depends_on:
      postgres_gitea:
        condition: service_healthy

  # create gitea admin after the service is up
  # task-create-admin:
  #   image: alpine
  #   deploy:
  #     restart_policy:
  #       condition: on-failure
  #     replicas: 1
  #   # docker compose stand-alone restart policy for tasks
  #   restart: on-failure
  #   entrypoint: sh -c "gitea admin user create --name admin2 --password theadmin --email admin2@lol.kek --admin"
  #   depends_on:
  #     gitea:
  #       condition: service_healthy

volumes:
  certs:

networks:
  gitea-net: